- name: update test container state
  docker_container:
    capabilities:
      - SYS_ADMIN
    image: "{{ item.image|d(test_playground.image_name) }}:{{ item.tag }}"
    name: &name "{{ test_playground.container_name_prefix }}{{ loop.index0 }}"
    state: "{{ test_playground.state }}"
    volumes: /sys/fs/cgroup:/sys/fs/cgroup:ro
  loop: &loop "{{ test_playground.deployment }}"

- name: add test container host
  add_host:
    ansible_connection: docker
    ansible_user: "{{ item.user|d('root') }}"
    groups: "{{ item.groups|d([])|join(',') }}"
    name: *name
  when:
    - test_playground.state == "present"
